# Generated by Django 2.1 on 2021-06-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutiveWordsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_pairs', models.CharField(max_length=1000)),
                ('times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=4000)),
                ('date', models.CharField(max_length=20)),
                ('variant', models.CharField(max_length=1000)),
                ('images', models.CharField(max_length=2083)),
                ('verified', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('product', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2083)),
                ('avg_polarity', models.FloatField(default=0.0)),
                ('sentiment', models.CharField(default='No Info', max_length=10)),
            ],
        ),
    ]
