# Generated by Django 3.2.4 on 2021-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210618_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='consecutivewordstable',
            name='product_id',
            field=models.CharField(default='No Product', max_length=300),
        ),
        migrations.AddField(
            model_name='reviewtable',
            name='product_id',
            field=models.CharField(default='No Product', max_length=300),
        ),
    ]
