# Generated by Django 3.2.4 on 2021-06-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210619_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutivewordstable',
            name='product_id',
            field=models.CharField(default='No Product', max_length=50),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='product_id',
            field=models.CharField(default='No Product', max_length=50),
        ),
    ]
