# Generated by Django 3.2.4 on 2021-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210619_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='content',
            field=models.CharField(max_length=6000),
        ),
    ]
