# Generated by Django 3.2.4 on 2021-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_reviewtable_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='variant',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
