# Generated by Django 3.2.4 on 2021-06-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_reviewtable_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('main_cat', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('asin', models.CharField(max_length=50)),
                ('imageURLHighRes', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTableNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField()),
                ('verified', models.CharField(max_length=10)),
                ('reviewTime', models.CharField(max_length=20)),
                ('reviewerID', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=1000, null=True)),
                ('reviewerName', models.CharField(max_length=300)),
                ('reviewText', models.CharField(max_length=6000)),
                ('summary', models.CharField(max_length=500)),
                ('unixReviewTime', models.DateField()),
                ('vote', models.FloatField(null=True)),
                ('image', models.CharField(max_length=2083, null=True)),
            ],
        ),
    ]
