# Generated by Django 3.2.4 on 2021-06-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_producttable_reviewtablenew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsecutiveWordsTable',
        ),
    ]
