# Generated by Django 3.2.4 on 2021-06-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_delete_consecutivewordstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttable',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
