# Generated by Django 3.2.4 on 2021-06-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_producttable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtablenew',
            name='reviewText',
            field=models.CharField(max_length=8000),
        ),
    ]
