# Generated by Django 3.2.4 on 2021-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_alter_reviewtablenew_reviewtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtablenew',
            name='avg_polarity',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='reviewtablenew',
            name='sentiment',
            field=models.CharField(default='No Info', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reviewtablenew',
            name='reviewText',
            field=models.CharField(max_length=11000),
        ),
    ]
