# Generated by Django 3.2.4 on 2021-06-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20210624_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewtablenew',
            name='neg_sentence_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='reviewtablenew',
            name='pos_sentence_rate',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
