# Generated by Django 2.1 on 2021-06-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewtable',
            name='author',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reviewtable',
            name='product',
            field=models.CharField(max_length=500),
        ),
    ]
